DROP DATABASE IF EXISTS smartcampus;
CREATE DATABASE smartcampus CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE smartcampus;

CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(50) NOT NULL,
  name VARCHAR(150) DEFAULT NULL,
  email VARCHAR(150) DEFAULT NULL,
  phone VARCHAR(30) DEFAULT NULL,
  linked_id INT DEFAULT NULL,
  status VARCHAR(30) DEFAULT 'active',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE departments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  code VARCHAR(30) DEFAULT NULL,
  hod_id INT DEFAULT NULL,
  status VARCHAR(30) DEFAULT 'active',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE teachers (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT DEFAULT NULL,
  teacher_code VARCHAR(50) DEFAULT NULL,
  name VARCHAR(150) DEFAULT NULL,
  dept VARCHAR(120) DEFAULT NULL,
  designation VARCHAR(120) DEFAULT NULL,
  email VARCHAR(150) DEFAULT NULL,
  phone VARCHAR(30) DEFAULT NULL,
  dob DATE DEFAULT NULL,
  status VARCHAR(30) DEFAULT 'active',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_teachers_user_id (user_id)
) ENGINE=InnoDB;

CREATE TABLE students (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT DEFAULT NULL,
  reg_no VARCHAR(60) DEFAULT NULL,
  name VARCHAR(150) DEFAULT NULL,
  dept VARCHAR(120) DEFAULT NULL,
  year VARCHAR(20) DEFAULT NULL,
  semester VARCHAR(20) DEFAULT NULL,
  section VARCHAR(20) DEFAULT NULL,
  admission_year INT DEFAULT NULL,
  dob DATE DEFAULT NULL,
  email VARCHAR(150) DEFAULT NULL,
  phone VARCHAR(30) DEFAULT NULL,
  status VARCHAR(30) DEFAULT 'active',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_students_reg_no (reg_no),
  INDEX idx_students_user_id (user_id)
) ENGINE=InnoDB;

CREATE TABLE subjects (
  id INT AUTO_INCREMENT PRIMARY KEY,
  subject_code VARCHAR(50) DEFAULT NULL,
  subject_name VARCHAR(180) DEFAULT NULL,
  dept VARCHAR(120) DEFAULT NULL,
  semester VARCHAR(20) DEFAULT NULL,
  credits INT DEFAULT NULL,
  status VARCHAR(30) DEFAULT 'active',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE classes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  class_name VARCHAR(120) DEFAULT NULL,
  department VARCHAR(120) DEFAULT NULL,
  year VARCHAR(20) DEFAULT NULL,
  semester VARCHAR(20) DEFAULT NULL,
  section VARCHAR(20) DEFAULT NULL,
  status VARCHAR(30) DEFAULT 'active',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE hods (
  id INT AUTO_INCREMENT PRIMARY KEY,
  teacher_id INT DEFAULT NULL,
  department VARCHAR(120) DEFAULT NULL,
  assigned_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  status VARCHAR(30) DEFAULT 'active',
  INDEX idx_hods_teacher_id (teacher_id)
) ENGINE=InnoDB;

CREATE TABLE teacher_courses (
  id INT AUTO_INCREMENT PRIMARY KEY,
  teacher_id INT DEFAULT NULL,
  course_id INT DEFAULT NULL,
  subject_id INT DEFAULT NULL,
  subject_name VARCHAR(180) DEFAULT NULL,
  dept VARCHAR(120) DEFAULT NULL,
  semester VARCHAR(20) DEFAULT NULL,
  year VARCHAR(20) DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_teacher_courses_teacher_id (teacher_id)
) ENGINE=InnoDB;

CREATE TABLE subject_controllers (
  id INT AUTO_INCREMENT PRIMARY KEY,
  teacher_id INT DEFAULT NULL,
  subject_id INT DEFAULT NULL,
  dept VARCHAR(120) DEFAULT NULL,
  semester VARCHAR(20) DEFAULT NULL,
  assigned_by INT DEFAULT NULL,
  status VARCHAR(30) DEFAULT 'active',
  assigned_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_subject_controllers_teacher_id (teacher_id)
) ENGINE=InnoDB;

CREATE TABLE subject_staff_assignments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  subject_id INT DEFAULT NULL,
  teacher_id INT DEFAULT NULL,
  class_id INT DEFAULT NULL,
  coordinator_id INT DEFAULT NULL,
  status VARCHAR(30) DEFAULT 'pending',
  remarks TEXT DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE class_coordinators (
  id INT AUTO_INCREMENT PRIMARY KEY,
  class_id INT DEFAULT NULL,
  teacher_id INT DEFAULT NULL,
  department VARCHAR(120) DEFAULT NULL,
  year VARCHAR(20) DEFAULT NULL,
  section VARCHAR(20) DEFAULT NULL,
  assigned_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  status VARCHAR(30) DEFAULT 'active'
) ENGINE=InnoDB;

CREATE TABLE class_subject_plans (
  id INT AUTO_INCREMENT PRIMARY KEY,
  class_id INT DEFAULT NULL,
  subject_id INT DEFAULT NULL,
  teacher_id INT DEFAULT NULL,
  plan_text TEXT DEFAULT NULL,
  status VARCHAR(30) DEFAULT 'pending',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE class_timetable (
  id INT AUTO_INCREMENT PRIMARY KEY,
  class_id INT DEFAULT NULL,
  subject_id INT DEFAULT NULL,
  teacher_id INT DEFAULT NULL,
  day_of_week VARCHAR(20) DEFAULT NULL,
  start_time TIME DEFAULT NULL,
  end_time TIME DEFAULT NULL,
  room_no VARCHAR(40) DEFAULT NULL,
  status VARCHAR(30) DEFAULT 'pending',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE timetable (
  id INT AUTO_INCREMENT PRIMARY KEY,
  class_id INT DEFAULT NULL,
  subject_id INT DEFAULT NULL,
  teacher_id INT DEFAULT NULL,
  day_of_week VARCHAR(20) DEFAULT NULL,
  start_time TIME DEFAULT NULL,
  end_time TIME DEFAULT NULL,
  room_no VARCHAR(40) DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE timetable_conflicts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  timetable_id INT DEFAULT NULL,
  conflict_type VARCHAR(80) DEFAULT NULL,
  details TEXT DEFAULT NULL,
  resolved TINYINT(1) DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE attendance_sessions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  subject_id INT DEFAULT NULL,
  class_id INT DEFAULT NULL,
  teacher_id INT DEFAULT NULL,
  date DATE DEFAULT NULL,
  start_time DATETIME DEFAULT NULL,
  end_time DATETIME DEFAULT NULL,
  status VARCHAR(30) DEFAULT 'active',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE attendance_records (
  id INT AUTO_INCREMENT PRIMARY KEY,
  session_id INT DEFAULT NULL,
  student_id INT DEFAULT NULL,
  status VARCHAR(20) DEFAULT 'present',
  marked_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  notes TEXT DEFAULT NULL,
  INDEX idx_attendance_records_session_id (session_id),
  INDEX idx_attendance_records_student_id (student_id)
) ENGINE=InnoDB;

CREATE TABLE marks (
  id INT AUTO_INCREMENT PRIMARY KEY,
  student_id INT DEFAULT NULL,
  subject_id INT DEFAULT NULL,
  teacher_id INT DEFAULT NULL,
  exam_type VARCHAR(60) DEFAULT NULL,
  marks_obtained DECIMAL(7,2) DEFAULT NULL,
  max_marks DECIMAL(7,2) DEFAULT NULL,
  exam_date DATE DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE grades (
  id INT AUTO_INCREMENT PRIMARY KEY,
  student_id INT DEFAULT NULL,
  subject_id INT DEFAULT NULL,
  grade VARCHAR(10) DEFAULT NULL,
  gpa DECIMAL(4,2) DEFAULT NULL,
  semester VARCHAR(20) DEFAULT NULL,
  year VARCHAR(20) DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE fee_structure (
  id INT AUTO_INCREMENT PRIMARY KEY,
  dept VARCHAR(120) DEFAULT NULL,
  year VARCHAR(20) DEFAULT NULL,
  semester VARCHAR(20) DEFAULT NULL,
  amount DECIMAL(12,2) DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE student_fees (
  id INT AUTO_INCREMENT PRIMARY KEY,
  student_id INT DEFAULT NULL,
  total_amount DECIMAL(12,2) DEFAULT 0,
  paid_amount DECIMAL(12,2) DEFAULT 0,
  due_amount DECIMAL(12,2) DEFAULT 0,
  due_date DATE DEFAULT NULL,
  status VARCHAR(30) DEFAULT 'pending',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE fee_payments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  student_id INT DEFAULT NULL,
  fee_id INT DEFAULT NULL,
  amount DECIMAL(12,2) DEFAULT 0,
  payment_mode VARCHAR(40) DEFAULT NULL,
  reference_no VARCHAR(100) DEFAULT NULL,
  paid_on DATETIME DEFAULT CURRENT_TIMESTAMP,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE live_locations (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT DEFAULT NULL,
  student_id INT DEFAULT NULL,
  latitude DECIMAL(10,7) DEFAULT NULL,
  longitude DECIMAL(10,7) DEFAULT NULL,
  accuracy_m DECIMAL(8,2) DEFAULT NULL,
  recorded_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_live_locations_student_id (student_id)
) ENGINE=InnoDB;

CREATE TABLE student_locations (
  id INT AUTO_INCREMENT PRIMARY KEY,
  student_id INT DEFAULT NULL,
  latitude DECIMAL(10,7) DEFAULT NULL,
  longitude DECIMAL(10,7) DEFAULT NULL,
  location_label VARCHAR(200) DEFAULT NULL,
  recorded_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE student_live_location (
  id INT AUTO_INCREMENT PRIMARY KEY,
  student_id INT DEFAULT NULL,
  latitude DECIMAL(10,7) DEFAULT NULL,
  longitude DECIMAL(10,7) DEFAULT NULL,
  location_label VARCHAR(200) DEFAULT NULL,
  recorded_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE student_entry_log (
  id INT AUTO_INCREMENT PRIMARY KEY,
  student_id INT DEFAULT NULL,
  entry_type VARCHAR(20) DEFAULT NULL,
  gate_name VARCHAR(80) DEFAULT NULL,
  logged_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  remarks TEXT DEFAULT NULL
) ENGINE=InnoDB;

CREATE TABLE student_campus_status (
  id INT AUTO_INCREMENT PRIMARY KEY,
  student_id INT DEFAULT NULL,
  status VARCHAR(40) DEFAULT 'inside',
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE sos_alerts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  student_id INT DEFAULT NULL,
  message TEXT DEFAULT NULL,
  latitude DECIMAL(10,7) DEFAULT NULL,
  longitude DECIMAL(10,7) DEFAULT NULL,
  priority VARCHAR(20) DEFAULT 'high',
  status VARCHAR(30) DEFAULT 'open',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  resolved_at DATETIME DEFAULT NULL
) ENGINE=InnoDB;

CREATE TABLE sos_incident_log (
  id INT AUTO_INCREMENT PRIMARY KEY,
  sos_id INT DEFAULT NULL,
  action_taken TEXT DEFAULT NULL,
  acted_by INT DEFAULT NULL,
  acted_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE sos_context_analysis (
  id INT AUTO_INCREMENT PRIMARY KEY,
  sos_id INT DEFAULT NULL,
  risk_score DECIMAL(5,2) DEFAULT NULL,
  context_summary TEXT DEFAULT NULL,
  analyzed_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE policy_rules (
  id INT AUTO_INCREMENT PRIMARY KEY,
  rule_key VARCHAR(120) DEFAULT NULL,
  rule_value TEXT DEFAULT NULL,
  status VARCHAR(30) DEFAULT 'active',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE policy_compliance_violations (
  id INT AUTO_INCREMENT PRIMARY KEY,
  student_id INT DEFAULT NULL,
  rule_id INT DEFAULT NULL,
  details TEXT DEFAULT NULL,
  severity VARCHAR(20) DEFAULT 'medium',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE policy_early_warnings (
  id INT AUTO_INCREMENT PRIMARY KEY,
  student_id INT DEFAULT NULL,
  warning_type VARCHAR(80) DEFAULT NULL,
  details TEXT DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE risk_history (
  id INT AUTO_INCREMENT PRIMARY KEY,
  student_id INT DEFAULT NULL,
  risk_score DECIMAL(5,2) DEFAULT NULL,
  risk_level VARCHAR(20) DEFAULT NULL,
  notes TEXT DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE student_digital_twin (
  id INT AUTO_INCREMENT PRIMARY KEY,
  student_id INT DEFAULT NULL,
  twin_state JSON DEFAULT NULL,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE twin_progress_snapshots (
  id INT AUTO_INCREMENT PRIMARY KEY,
  student_id INT DEFAULT NULL,
  snapshot_data JSON DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE sentiment_feedback (
  id INT AUTO_INCREMENT PRIMARY KEY,
  student_id INT DEFAULT NULL,
  feedback_text TEXT DEFAULT NULL,
  sentiment_score DECIMAL(5,2) DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE sentiment_alerts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  student_id INT DEFAULT NULL,
  alert_text TEXT DEFAULT NULL,
  severity VARCHAR(20) DEFAULT 'medium',
  status VARCHAR(30) DEFAULT 'open',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE sentiment_analysis_trends (
  id INT AUTO_INCREMENT PRIMARY KEY,
  student_id INT DEFAULT NULL,
  period_label VARCHAR(60) DEFAULT NULL,
  sentiment_avg DECIMAL(5,2) DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE form_submissions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  student_id INT DEFAULT NULL,
  form_type VARCHAR(100) DEFAULT NULL,
  form_data JSON DEFAULT NULL,
  status VARCHAR(30) DEFAULT 'submitted',
  review_status VARCHAR(30) DEFAULT 'pending',
  submitted_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE form_notifications (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT DEFAULT NULL,
  form_submission_id INT DEFAULT NULL,
  message TEXT DEFAULT NULL,
  is_read TINYINT(1) DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE form_workflow_audit (
  id INT AUTO_INCREMENT PRIMARY KEY,
  form_submission_id INT DEFAULT NULL,
  action_by INT DEFAULT NULL,
  action_name VARCHAR(80) DEFAULT NULL,
  remarks TEXT DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE coordinator_assignment_history (
  id INT AUTO_INCREMENT PRIMARY KEY,
  coordinator_id INT DEFAULT NULL,
  class_id INT DEFAULT NULL,
  assigned_by INT DEFAULT NULL,
  assigned_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  removed_at DATETIME DEFAULT NULL,
  remarks TEXT DEFAULT NULL
) ENGINE=InnoDB;

CREATE TABLE coordinator_recommendations (
  id INT AUTO_INCREMENT PRIMARY KEY,
  class_id INT DEFAULT NULL,
  teacher_id INT DEFAULT NULL,
  score DECIMAL(6,2) DEFAULT NULL,
  reason TEXT DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE student_logout_requests (
  id INT AUTO_INCREMENT PRIMARY KEY,
  student_id INT DEFAULT NULL,
  reason TEXT DEFAULT NULL,
  status VARCHAR(30) DEFAULT 'pending',
  requested_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  decided_by INT DEFAULT NULL,
  decided_at DATETIME DEFAULT NULL,
  decision_notes TEXT DEFAULT NULL
) ENGINE=InnoDB;

CREATE TABLE system_settings (
  id INT AUTO_INCREMENT PRIMARY KEY,
  setting_key VARCHAR(120) NOT NULL UNIQUE,
  setting_value TEXT DEFAULT NULL,
  updated_by INT DEFAULT NULL,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE teacher_biometric_log (
  id INT AUTO_INCREMENT PRIMARY KEY,
  teacher_id INT DEFAULT NULL,
  attendance_date DATE DEFAULT NULL,
  check_in DATETIME DEFAULT NULL,
  check_out DATETIME DEFAULT NULL,
  device_info VARCHAR(200) DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE hotspot_rejection_log (
  id INT AUTO_INCREMENT PRIMARY KEY,
  student_id INT DEFAULT NULL,
  reason TEXT DEFAULT NULL,
  rejected_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE academic_dependencies (
  id INT AUTO_INCREMENT PRIMARY KEY,
  module_name VARCHAR(120) DEFAULT NULL,
  dependency_name VARCHAR(120) DEFAULT NULL,
  status VARCHAR(30) DEFAULT 'active',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE academic_optimization_suggestions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  student_id INT DEFAULT NULL,
  suggestion TEXT DEFAULT NULL,
  priority VARCHAR(20) DEFAULT 'medium',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE affairs_counseling (
  id INT AUTO_INCREMENT PRIMARY KEY,
  student_id INT DEFAULT NULL,
  counselor_id INT DEFAULT NULL,
  session_date DATE DEFAULT NULL,
  notes TEXT DEFAULT NULL,
  status VARCHAR(30) DEFAULT 'scheduled',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE affairs_events (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(180) DEFAULT NULL,
  event_date DATE DEFAULT NULL,
  venue VARCHAR(180) DEFAULT NULL,
  details TEXT DEFAULT NULL,
  status VARCHAR(30) DEFAULT 'active',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE affairs_health (
  id INT AUTO_INCREMENT PRIMARY KEY,
  student_id INT DEFAULT NULL,
  issue_type VARCHAR(120) DEFAULT NULL,
  notes TEXT DEFAULT NULL,
  status VARCHAR(30) DEFAULT 'open',
  reported_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE affairs_incidents (
  id INT AUTO_INCREMENT PRIMARY KEY,
  student_id INT DEFAULT NULL,
  incident_type VARCHAR(120) DEFAULT NULL,
  incident_date DATE DEFAULT NULL,
  details TEXT DEFAULT NULL,
  action_taken TEXT DEFAULT NULL,
  status VARCHAR(30) DEFAULT 'open',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE user_tokens (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT DEFAULT NULL,
  token VARCHAR(255) DEFAULT NULL,
  expires_at DATETIME DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_user_tokens_user_id (user_id)
) ENGINE=InnoDB;

INSERT INTO system_settings (setting_key, setting_value) VALUES
('college_end_time', '17:00:00'),
('logout_policy_enabled', '1');
